### ISSUE TITLE
Wireframe : Docs

### ISSUE THREAD

**Issue by rayanejsilva** [JTLiberona/loruki-website#16]
- [x] Design the wireframe of the Docs page.

**Comment by rayanejsilva** [comment]
This is done. Waiting for review!

**Comment by katsmamina** [comment]
I love the style! @rayanejsilva 
Just thought that in the future, it would be great to discuss styling in advance, as at the moment our wireframes look very different :)

**Comment by rayanejsilva** [comment]
@katsmamina Thank you! 😊  For this module, I think it is not a problem that we have different designs (In the ux-ui-design module, we will learn more about wireframes styles). Our goal is to have wireframes that provide a clear overview of our page structure. But in the future, we can discuss this topic in advance. I just love to play with draw.io 😂.
