### ISSUE TITLE
Communication Plan

### ISSUE THREAD

**Issue by rayanejsilva** [JTLiberona/loruki-website#5]
##Scheduling

Formulate our project management communication plan.

- [x] Determine frequency (how often we will get in touch)
- [x] Communication channels (what we will discuss on each channel)
  - [x] Slack Messaging
  - [x] Zoom Video Calls
  - [x] Issues
  - [x] Pull Requests
- [x] Availability schedule
- [x] Decide how we will evaluate our plan and adjust it (review day?)

**Comment by colevandersWands** [comment]
You can set up the /planning README with a poll and some messaging on Slack, then one person can just copy the results into the README.   After that you can update your times by PR - no need to schedule a whole meeting for this. You should try to save your meeting time to talk about the project
